apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tuna
  namespace: prod-sea
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: tuna
    spec:
      containers:
        - args:
            - --verbose=False
            - --secret=?{plain:$PWD/secrets/targets/prod-sea/tuna|randomstr}
            - --brine
            - --canned
          image: alledm/tuna:v2.0.0
          name: tuna
          volumeMounts:
            - mountPath: /tmp
              name: data
              readOnly: true
      volumes:
        - configMap:
            name: readme
          name: data
